apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - db-deployment.yml
  - db-service.yml
  - redis-deployment.yml
  - redis-service.yml
  - result-deployment.yml
  - result-service.yml
  - vote-deployment.yml
  - vote-service.yml
  - worker.yml

